### PR TITLE
Fixed encoding errors

### PR DESCRIPTION
**Pull request by 269Seahorse**
Fixed encoding making song title/subtitle garbled characters

### CODE REVIEW

**Comment by AlecJY** [comment]
In my personal experience, I have encountered TJA files encoded in Windows-31J (the Windows variant of Shift_JIS) quite frequently. However, UTF-8 encoding is also commonly used. Therefore, I think that adding an argument to switch between Windows-31J and UTF-8 encoding would be a better option.

**Comment by 269Seahorse** [comment]
I have edited my code to add UTF-8 as an option

**Comment by AlecJY** [comment]
Another point is to clean up your commits. You can accomplish this by utilizing interactive rebase (`git rebase -i`) to make adjustments to your commit history. You can use `drop` to eliminate unnecessary commits and use `squash`/`fixup` to merge similar commits into a single commit.

Last, make sure there are no merge commits in your commit history. The merge commit would be removed when you rebased your branch in the previous step. 

Thank you for your contribution. If you have any questions, feel free to ask me.

**Comment by 269Seahorse** [comment]
I've tried my best to clean up my commits, please tell me if I have to do anything else or if I did something wrong. 
Thank you!

**Comment by AlecJY** [comment]
Only three small problems need to be improved.

First, it seems that you rebase the branch onto an older commit and other changes which don't belong to the issue also merged into your commit. Rebase the branch on the latest commit (7df4d4e) again with `git rebase 7df4d4e` should solve the problem.

Second, the `lines` variable defined in line 17 and 19 of [TJASimpleParser.kt](https://github.com/AlecJY/TaikoWebSongImportTool/pull/3/files#diff-7c8cd8d8f38a3cb12784fa79da0468a495b8d14391fe4b2321f5ea5f6fcd5a68) should be defined outside the if statement.

Ex:
```kotlin
fun parseTJA(file: File, category: Genre, similarFile: Boolean, utf8: Boolean): TaikoWebSong {
    val lines: List<String>;
    if (utf8) {
        lines = file.readLines(StandardCharsets.UTF_8);
    } else {
        lines = file.readLines(Charset.forName("Windows-31J"));
    }
```

Lastly, It looks like you write the same message two times in the commit message. You can edit your last commit by running `git commit --amend` to eliminate the redundent message.

If you still have any questions, feel free to ask me.

**Comment by 269Seahorse** [comment]
I've done the steps you have told me. I am not very familiar with Git so I may make many mistakes. Sorry for the convenience, and thank you for telling me what to do!

Please tell me if I have to do anything else, thank you!

**Comment by AlecJY** [comment]
It's OK. The commit looks good to me now. Thank you for your contribution.

**Pull request merged**
